# Generated by Django 4.0.4 on 2022-08-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComponentName', models.CharField(default='', max_length=32)),
                ('temperature', models.CharField(default='', max_length=32)),
                ('density', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('group', models.FloatField(default=0)),
            ],
        ),
    ]
