# Generated by Django 4.0.4 on 2022-08-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userinfo_mailnum_userinfo_phonenum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='mailnum',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phonenum',
        ),
    ]
